### ISSUE TITLE
TypeError: is not assignable to type TransportStream writable missing

### ISSUE THREAD

**Issue by sharifzadesina** [winstonjs/winston-daily-rotate-file#190]
```
error TS2322: Type '(DailyRotateFile | ConsoleTransportInstance)[]' is not assignable to type 'TransportStream | TransportStream[]'.
  Type '(DailyRotateFile | ConsoleTransportInstance)[]' is not assignable to type 'TransportStream[]'.
    Type 'DailyRotateFile | ConsoleTransportInstance' is not assignable to type 'TransportStream'.
      Type 'DailyRotateFile' is not assignable to type 'TransportStream'.
        Property 'writable' is missing in type 'DailyRotateFile'.
```

**Comment by mattberther** [comment]
@sharifzadesina Can you please provide details on what version you're using? Is this related to the TypeScript definitions?

@Slessi, do you see why this might be happening?

**Comment by Slessi** [comment]
No, works fine for me with `winston@3.1.0` and `winston-daily-rotate-file@3.5.0`.

Also worked with `winston-daily-rotate-file@3.4.0`

**Comment by sharifzadesina** [comment]
@Slessi I am using `winston@3.1.0` and `winston-daily-rotate-file@3.5.0`.
When I import it like this the error happens:
```ts
import DailyRotateFile from 'winston-daily-rotate-file';
// or like this
import DailyRotateFile = require("winston-daily-rotate-file");
```
But when I import it like this it works:
```js
const DailyRotateFile = require('winston-daily-rotate-file');
```
It is a type issue, cause it works when we include it in traditional way.

**Comment by Slessi** [comment]
@sharifzadesina 

- `import DailyRotateFile from 'winston-daily-rotate-file';` is wrong, this is not a default export
- `const DailyRotateFile = require('winston-daily-rotate-file');` will always work because it is not type checked, you will see the type as `any`
- `import DailyRotateFile = require("winston-daily-rotate-file");` is the correct way to do it

Show me the rest of your code and I will explain why it isn't working for you

**Comment by sharifzadesina** [comment]
@Slessi 
I have `"esModuleInterop": true` so the first example is also true.
Yes as I told, on the second-way, It works, cause it is a type problem.
Also it doesn't work on third-way, same error.
Here the code:
```ts
import DailyRotateFile from 'winston-daily-rotate-file';
// or
import DailyRotateFile = require('winston-daily-rotate-file');

var w = winston.createLogger({
  transports: [
    new winston.transports.Console({
      format: winston.format.printf(info => `[app] ${info.level}: ${info.message}`),
      silent: process.env.NODE_ENV === 'production'
    }),
    new DailyRotateFile({
      dirname: path.join(SERVER_PATH, 'storage', 'logs'),
      filename: 'app-%DATE%.log',
      maxFiles: '14d'
    }),
  ],
});
```

**Comment by mattberther** [comment]
Thanks @Slessi. Merged #192 and published as `winston-daily-rotate-file@3.5.1`.
